package com.example.util

object Localization {
    private val dictionary = mapOf(
        "en" to mapOf(
            "dashboard" to "Dashboard",
            "customers" to "Customers",
            "settings" to "Settings",
            "total_customers" to "Total Customers",
            "total_measurements" to "Total Measurements",
            "recent_30_days" to "Recent (30 Days)",
            "search_hint" to "Search by name, mobile, ID...",
            "recent_customers" to "Recent Customers",
            "quick_actions" to "Quick Actions",
            "add_customer" to "Add Customer",
            "view_all_customers" to "View All Customers",
            "no_recent_customers" to "No recent customers found.",
            "name" to "Customer Name",
            "mobile" to "Mobile Number",
            "alt_mobile" to "Alternate Mobile",
            "address" to "Address",
            "notes" to "Notes",
            "save" to "Save",
            "cancel" to "Cancel",
            "delete" to "Delete",
            "edit" to "Edit",
            "customer_id" to "Customer ID",
            "joined" to "Joined",
            "last_updated" to "Last Updated",
            "delete_customer_title" to "Delete Customer",
            "delete_customer_message" to "Are you sure you want to delete this customer? All their measurement history will be lost forever.",
            "measurement_history" to "Measurement History",
            "export_pdf" to "Export PDF",
            "add_measurement" to "Add Measurement",
            "no_measurements" to "No measurement records found.",
            "category_blouse" to "Blouse (બ્લાઉઝ)",
            "category_punjabi" to "Punjabi Dress (પંજાબી ડ્રેસ)",
            "punjabi_top" to "Top (ટોપ)",
            "punjabi_bottom" to "Salwar/Pant/Palazzo (સલવાર/પેન્ટ/પલાઝો)",
            "measurement_notes" to "Measurement Notes (e.g. pattern, neck style)",
            "all_fields_in_inches" to "All measurements are in inches (\")",
            "save_measurement" to "Save Measurement",
            "delete_measurement_title" to "Delete Measurement",
            "delete_measurement_message" to "Are you sure you want to delete this measurement record?",
            "shop_info" to "Shop Information",
            "shop_name" to "Shop Name",
            "owner_name" to "Owner Name",
            "language" to "App Language",
            "app_theme" to "App Theme",
            "theme_system" to "System",
            "theme_light" to "Light",
            "theme_dark" to "Dark",
            "backup_restore" to "Backup & Restore",
            "backup_desc" to "Export your customer and measurement records to a JSON file, or restore from a previous backup.",
            "export_backup" to "Export JSON Backup",
            "import_backup" to "Import JSON Backup",
            "save_shop_success" to "Shop settings saved successfully!",
            "edit_customer" to "Edit Customer Info",
            "search_customer" to "Search Customer",
            "select_customer" to "Select Customer",
            "validation_name_empty" to "Customer Name is required",
            "validation_mobile_invalid" to "Mobile must be 10-15 digits",
            "validation_measurement_empty" to "Please enter at least one measurement value"
        ),
        "gu" to mapOf(
            "dashboard" to "ડેેશબોર્ડ",
            "customers" to "ગ્રાહકો",
            "settings" to "સેટિંગ્સ",
            "total_customers" to "કુલ ગ્રાહકો",
            "total_measurements" to "કુલ માપ",
            "recent_30_days" to "નવા (છેલ્લા ૩૦ દિવસ)",
            "search_hint" to "નામ, મોબાઈલ કે ID થી શોધો...",
            "recent_customers" to "તાજેતરના ગ્રાહકો",
            "quick_actions" to "ઝડપી ક્રિયાઓ",
            "add_customer" to "નવો ગ્રાહક ઉમેરો",
            "view_all_customers" to "બધા ગ્રાહકો જુઓ",
            "no_recent_customers" to "કોઈ તાજેતરના ગ્રાહકો મળ્યા નથી.",
            "name" to "ગ્રાહકનું નામ",
            "mobile" to "મોબાઈલ નંબર",
            "alt_mobile" to "બીજો મોબાઈલ નંબર",
            "address" to "સરનામું",
            "notes" to "નોંધ (નોટ્સ)",
            "save" to "સાચવો",
            "cancel" to "રદ કરો",
            "delete" to "કાઢી નાખો",
            "edit" to "સુધારો",
            "customer_id" to "ગ્રાહક ID",
            "joined" to "જોડાયા તારીખ",
            "last_updated" to "છેલ્લો સુધારો",
            "delete_customer_title" to "ગ્રાહક કાઢી નાખો",
            "delete_customer_message" to "શું તમે ખરેખર આ ગ્રાહકને કાઢી નાખવા માંગો છો? તેમનો તમામ માપનો ઇતિહાસ કાયમ માટે કાઢી નાખવામાં આવશે.",
            "measurement_history" to "માપનો ઇતિહાસ",
            "export_pdf" to "PDF ડાઉનલોડ / શેર",
            "add_measurement" to "નવું માપ લો",
            "no_measurements" to "માપનો કોઈ રેકોર્ડ મળ્યો નથી.",
            "category_blouse" to "બ્લાઉઝ",
            "category_punjabi" to "પંજાબી ડ્રેસ",
            "punjabi_top" to "ટોપ",
            "punjabi_bottom" to "સલવાર/પેન્ટ/પલાઝો",
            "measurement_notes" to "માપ સંબંધિત નોંધ (દા.ત. ડિઝાઈન, ગળાની સ્ટાઈલ)",
            "all_fields_in_inches" to "તમામ માપ ઇંચ (\") માં છે",
            "save_measurement" to "માપ સાચવો",
            "delete_measurement_title" to "માપ કાઢી નાખો",
            "delete_measurement_message" to "શું તમે ખરેખર આ માપનો રેકોર્ડ કાઢી નાખવા માંગો છો?",
            "shop_info" to "દુકાનની માહિતી",
            "shop_name" to "દુકાનનું નામ",
            "owner_name" to "માલિકનું નામ",
            "language" to "એપની ભાષા",
            "app_theme" to "એપ થીમ",
            "theme_system" to "સિસ્ટમ મુજબ",
            "theme_light" to "લાઇટ મોડ",
            "theme_dark" to "ડાર્ક મોડ",
            "backup_restore" to "બેકઅપ અને રીસ્ટોર",
            "backup_desc" to "તમારા ગ્રાહકો અને માપના રેકોર્ડને JSON ફાઇલમાં એક્સપોર્ટ કરો અથવા જૂના બેકઅપમાંથી રીસ્ટોર કરો.",
            "export_backup" to "બેકઅપ એક્સપોર્ટ કરો (JSON)",
            "import_backup" to "બેકઅપ રીસ્ટોર કરો (JSON)",
            "save_shop_success" to "દુકાનની માહિતી સફળતાપૂર્વક સાચવવામાં આવી!",
            "edit_customer" to "ગ્રાહકની માહિતી સુધારો",
            "search_customer" to "ગ્રાહક શોધો",
            "select_customer" to "ગ્રાહક પસંદ કરો",
            "validation_name_empty" to "ગ્રાહકનું નામ જરૂરી છે",
            "validation_mobile_invalid" to "મોબાઈલ નંબર ૧૦-૧૫ આંકડાનો હોવો જોઈએ",
            "validation_measurement_empty" to "કૃપા કરીને ઓછામાં ઓછું એક માપ દાખલ કરો"
        )
    )

    fun get(key: String, language: String): String {
        return dictionary[language]?.get(key) ?: dictionary["en"]?.get(key) ?: key
    }
}
